# file: .goreleaser.yml
# version: 1.0.0
# guid: c3d4e5f6-g7h8-9012-cdef-123456789012

# gcommon is a library, not a binary release
# This config is for potential future CLI tools

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - skip: true

archives:
  - id: gcommon-source
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_source
    files:
      - LICENSE
      - README.md
      - "**/*.go"
      - go.mod
      - go.sum

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

release:
  github:
    owner: jdfalk
    name: gcommon
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
