# file: .github/workflows/sync-protos.yml
# version: 1.0.0
# guid: sync-protos-workflow-gcommon-go

name: Sync Protocol Buffers

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC
  workflow_dispatch:
  repository_dispatch:
    types: [proto-updated]

jobs:
  sync-protos:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install buf
      run: |
        BUF_VERSION="1.26.1"
        curl -sSL "https://github.com/bufbuild/buf/releases/download/v${BUF_VERSION}/buf-$(uname -s)-$(uname -m)" -o "/usr/local/bin/buf"
        chmod +x "/usr/local/bin/buf"
        
    - name: Setup dependencies
      run: make setup
      
    - name: Sync protocol buffers from gcommon
      run: make sync-protos
      
    - name: Generate code
      run: make generate
      
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "feat(proto): sync protocol buffers from gcommon

        Automated sync of protocol buffer definitions and regeneration of language-specific code.
        
        Generated by: GitHub Actions workflow"
        git push
